// DOM(Document Object Model)
//    When the browser first loads and reads Html code 
//    it creates DOM, a tree like structure representing 
//    html code as a family tree. Then each HTML element 
//    is converted to dom node via brower.

//    Using the Dom nodes properties and methods(id,classname,tags), we 
//    can manipulate Dom nodes using javascript.

    //  Image: refer to dom1.jpeg 